# Generated by Django 4.2.3 on 2023-07-06 06:09

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images", verbose_name="Image"
                    ),
                ),
            ],
        ),
    ]
